[package]
name = "remedy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
remediate = "0.2.0"
clap = { version = "4.3.3", features = ["derive"] }
termion = "2.0.1"
strum = { version = "0.25.0", features = ["derive"] }