[package]
name = "remedy"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.3"
pest_meta = "2.7.3"
pest_vm = "2.7.3"
toml = "0.7.6"
serde = { version = "1.0.188", features = ["derive"] }
tower-lsp = "0.20.0"
tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1.0.75"
